# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(887, 712)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    border-image: url(:/arka/konser-nedir-konser-ne-demek-biletino-1124.jpg);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.name_lbl = QtWidgets.QLabel(self.centralwidget)
        self.name_lbl.setGeometry(QtCore.QRect(70, 20, 55, 16))
        self.name_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.name_lbl.setObjectName("name_lbl")
        self.surname_lbl = QtWidgets.QLabel(self.centralwidget)
        self.surname_lbl.setGeometry(QtCore.QRect(310, 20, 71, 16))
        self.surname_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"")
        self.surname_lbl.setObjectName("surname_lbl")
        self.age_lbl = QtWidgets.QLabel(self.centralwidget)
        self.age_lbl.setGeometry(QtCore.QRect(70, 60, 55, 16))
        self.age_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.age_lbl.setObjectName("age_lbl")
        self.name_line = QtWidgets.QLineEdit(self.centralwidget)
        self.name_line.setGeometry(QtCore.QRect(110, 20, 113, 22))
        self.name_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.name_line.setObjectName("name_line")
        self.surname_line = QtWidgets.QLineEdit(self.centralwidget)
        self.surname_line.setGeometry(QtCore.QRect(380, 20, 113, 22))
        self.surname_line.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.surname_line.setObjectName("surname_line")
        self.age_line = QtWidgets.QLineEdit(self.centralwidget)
        self.age_line.setGeometry(QtCore.QRect(110, 60, 113, 22))
        self.age_line.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.age_line.setObjectName("age_line")
        self.bilet_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.bilet_groupbox.setGeometry(QtCore.QRect(60, 210, 241, 161))
        self.bilet_groupbox.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.bilet_groupbox.setFlat(True)
        self.bilet_groupbox.setObjectName("bilet_groupbox")
        self.vip_radio = QtWidgets.QRadioButton(self.bilet_groupbox)
        self.vip_radio.setGeometry(QtCore.QRect(10, 40, 95, 20))
        self.vip_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.vip_radio.setObjectName("vip_radio")
        self.normal_radio = QtWidgets.QRadioButton(self.bilet_groupbox)
        self.normal_radio.setGeometry(QtCore.QRect(10, 100, 95, 20))
        self.normal_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.normal_radio.setObjectName("normal_radio")
        self.vip_koltuk_lbl = QtWidgets.QLabel(self.centralwidget)
        self.vip_koltuk_lbl.setGeometry(QtCore.QRect(350, 250, 91, 16))
        self.vip_koltuk_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.vip_koltuk_lbl.setObjectName("vip_koltuk_lbl")
        self.vip_koltuk = QtWidgets.QLineEdit(self.centralwidget)
        self.vip_koltuk.setGeometry(QtCore.QRect(430, 250, 113, 22))
        self.vip_koltuk.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.vip_koltuk.setObjectName("vip_koltuk")
        self.sanatcilar_groupbax = QtWidgets.QGroupBox(self.centralwidget)
        self.sanatcilar_groupbax.setGeometry(QtCore.QRect(80, 110, 661, 61))
        self.sanatcilar_groupbax.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.sanatcilar_groupbax.setFlat(True)
        self.sanatcilar_groupbax.setObjectName("sanatcilar_groupbax")
        self.sanatci_uc_radio = QtWidgets.QRadioButton(self.sanatcilar_groupbax)
        self.sanatci_uc_radio.setGeometry(QtCore.QRect(260, 30, 131, 20))
        self.sanatci_uc_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.sanatci_uc_radio.setObjectName("sanatci_uc_radio")
        self.sanatci_bir_radio = QtWidgets.QRadioButton(self.sanatcilar_groupbax)
        self.sanatci_bir_radio.setGeometry(QtCore.QRect(50, 30, 95, 20))
        self.sanatci_bir_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.sanatci_bir_radio.setObjectName("sanatci_bir_radio")
        self.sanatci_dort_radio = QtWidgets.QRadioButton(self.sanatcilar_groupbax)
        self.sanatci_dort_radio.setGeometry(QtCore.QRect(390, 30, 121, 20))
        self.sanatci_dort_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.sanatci_dort_radio.setObjectName("sanatci_dort_radio")
        self.sanatci_bes_radio = QtWidgets.QRadioButton(self.sanatcilar_groupbax)
        self.sanatci_bes_radio.setGeometry(QtCore.QRect(520, 30, 95, 20))
        self.sanatci_bes_radio.setStyleSheet("color: rgb(255, 255, 255);")
        self.sanatci_bes_radio.setObjectName("sanatci_bes_radio")
        self.sanatci_iki = QtWidgets.QRadioButton(self.sanatcilar_groupbax)
        self.sanatci_iki.setGeometry(QtCore.QRect(160, 30, 95, 20))
        self.sanatci_iki.setStyleSheet("color: rgb(255, 255, 255);")
        self.sanatci_iki.setObjectName("sanatci_iki")
        self.ucret_lbl = QtWidgets.QLabel(self.centralwidget)
        self.ucret_lbl.setGeometry(QtCore.QRect(310, 60, 141, 16))
        self.ucret_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.ucret_lbl.setObjectName("ucret_lbl")
        self.satin_al = QtWidgets.QPushButton(self.centralwidget)
        self.satin_al.setGeometry(QtCore.QRect(190, 490, 181, 61))
        self.satin_al.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(170, 85, 127);\n"
"\n"
"color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ikonlar/onlineshopping_120797.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.satin_al.setIcon(icon)
        self.satin_al.setIconSize(QtCore.QSize(40, 40))
        self.satin_al.setAutoDefault(False)
        self.satin_al.setFlat(False)
        self.satin_al.setObjectName("satin_al")
        self.iptal_et = QtWidgets.QPushButton(self.centralwidget)
        self.iptal_et.setGeometry(QtCore.QRect(450, 490, 181, 61))
        self.iptal_et.setStyleSheet("\n"
"background-color: rgb(170, 85, 127);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ikonlar/cancelform_85913.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.iptal_et.setIcon(icon1)
        self.iptal_et.setIconSize(QtCore.QSize(30, 30))
        self.iptal_et.setObjectName("iptal_et")
        self.dolu_vip_lbl = QtWidgets.QLabel(self.centralwidget)
        self.dolu_vip_lbl.setGeometry(QtCore.QRect(350, 270, 481, 31))
        self.dolu_vip_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.dolu_vip_lbl.setObjectName("dolu_vip_lbl")
        self.iptal_koltuk_lbl = QtWidgets.QLabel(self.centralwidget)
        self.iptal_koltuk_lbl.setGeometry(QtCore.QRect(350, 310, 241, 21))
        self.iptal_koltuk_lbl.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.iptal_koltuk_lbl.setObjectName("iptal_koltuk_lbl")
        self.koltuk_iptal_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.koltuk_iptal_txt.setGeometry(QtCore.QRect(590, 310, 113, 22))
        self.koltuk_iptal_txt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.koltuk_iptal_txt.setObjectName("koltuk_iptal_txt")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 350, 511, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.lbl_uyari = QtWidgets.QLabel(self.centralwidget)
        self.lbl_uyari.setGeometry(QtCore.QRect(20, 380, 851, 71))
        self.lbl_uyari.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.lbl_uyari.setText("")
        self.lbl_uyari.setObjectName("lbl_uyari")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 887, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_lbl.setText(_translate("MainWindow", "İsim:"))
        self.surname_lbl.setText(_translate("MainWindow", "Soyisim:"))
        self.age_lbl.setText(_translate("MainWindow", "Yaş:"))
        self.bilet_groupbox.setTitle(_translate("MainWindow", "Bilet Türü"))
        self.vip_radio.setText(_translate("MainWindow", "Vip"))
        self.normal_radio.setText(_translate("MainWindow", "Normal"))
        self.vip_koltuk_lbl.setText(_translate("MainWindow", "Koltuk No:"))
        self.sanatcilar_groupbax.setTitle(_translate("MainWindow", "Sanatçılar"))
        self.sanatci_uc_radio.setText(_translate("MainWindow", "The Weekend"))
        self.sanatci_bir_radio.setText(_translate("MainWindow", "Murda"))
        self.sanatci_dort_radio.setText(_translate("MainWindow", "Taylor Swift"))
        self.sanatci_bes_radio.setText(_translate("MainWindow", "Ezhel"))
        self.sanatci_iki.setText(_translate("MainWindow", "Lil Zey"))
        self.ucret_lbl.setText(_translate("MainWindow", "Ücret:"))
        self.satin_al.setText(_translate("MainWindow", "Satın al"))
        self.iptal_et.setText(_translate("MainWindow", "İptal et"))
        self.dolu_vip_lbl.setText(_translate("MainWindow", "Dolu Koltuk:"))
        self.iptal_koltuk_lbl.setText(_translate("MainWindow", "İptal etmek İstedğiniz Bilet No:"))
        self.label.setText(_translate("MainWindow", "*Eğer normal biletiniz iptal etmek istiyorsanız bu kutucuğu kullanın*"))
import resim_rc
